### ISSUE TITLE
add installation instruction for linux

### ISSUE THREAD

**Issue by matkoniecz** [holman/spaceman-diff#5]
Probably it is relatively easy to figure out, by installation instructions would be nice.

**Comment by holman** [comment]
:+1: I'm not too sure what the best approach for installing them would be, but would definitely merge a pull if someone prepares one!

**Comment by resilva87** [comment]
Running Linux Mint 17 here, was simple as 
`sudo apt-get install jp2a imagemagick` :+1:

**Comment by holman** [comment]
Good enough for me! :) Thanks for the confirmation!
