### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by streeter** [holman/spaceman-diff#6]
I was going to make this into a Homebrew formula, but [they require](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#basic-instructions) that there be a tagged version. I'd suggest v1.0.

**Comment by holman** [comment]
Oooh, good point! Yeah, 1.0 works for me too.

https://github.com/holman/spaceman-diff/releases/tag/v1.0

**Comment by streeter** [comment]
:+1:
