### ISSUE TITLE
fatal error when an image has been deleted

### ISSUE THREAD

**Issue by jes5199** [holman/spaceman-diff#7]
I `rm`ed an image from a repo and then ran `git diff`, and got:

```
expr: not a decimal number: '3,'
fatal: external diff died, stopping at test/images/gooder-flag.png
```

**Comment by holman** [comment]
Good call! I had dealt with this earlier but then added the headers, which it was failing on. Fixed.

**Comment by jes5199** [comment]
:+1: that fixed it for me

**Comment by lfilho** [comment]
I'm running latest version as of this writing, installed via homebrew (macos). 

Although there is a deleted filed in the staging area, I don't have the `expr` error line, and the `stopping at` file does exist.
